# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07d333f1f21228a59cd3f01a031ce510e910e886b2320dbed1eeeacc46c41e7dd3f8bf3f624d591282e608a54404eb590b923564a707148edc556aeb5cb8de10

test:
  secret_key_base: 078c876010d75fba41a58dee3fd39e162a690294c3c8323f22feffb374d7ba3e3772a2d4d1f427ccff5f330b2cf3ca6dd74a1ee8ff42cf3c8ff2005791e53968

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
